Change preprocessor directives logic (STEEL_COMPILER, STEEL_OS, STEEL_OPENGL_API) steel::vector bugfix (resize) Convert some files to UTF-8 encoding Changes in file headers (new field 'File:') Fix some function definitions: name() -> name(void)
Error: DevC++ does not compile UTF-8 files

git-svn-id: svn://localhost/steel.new/trunk@251 99e027b2-380c-0410-a737-a5784e1a7bde